SORTING DATAFRAMES

In [3]:
import pandas as pd 
import numpy as np

In [10]:
#read the dataset 
data_BM = pd.read_csv(r'C:\Users\HomePC\IntroPython\Pandas_Part_1\Pandas Part 1\bigmart_data.csv')
#Drop the null values
data_BM = data_BM.dropna(how="any")
#view the top results
data_BM.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088

1.Soerting DataFrames 
.sort_values()-to sort pandas data frame by on or more columns 
.sort_indes()-to sort pandas data frame by row index

In [11]:
#sort by year by assending order which is the default
sorted_data = data_BM.sort_values(by='Outlet_Establishment_Year')
#print sorted data 
sorted_data [:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
2812,FDR60,14.30,Low Fat,0.130307,Baking Goods,75.7328,OUT013,1987,High,Tier 3,Supermarket Type1,617.8624
5938,NCJ06,20.10,Low Fat,0.034624,Household,118.9782,OUT013,1987,High,Tier 3,Supermarket Type1,1549.3166
3867,FDY38,13.60,Regular,0.119077,Dairy,231.2300,OUT013,1987,High,Tier 3,Supermarket Type1,2330.3000
1307,FDB37,20.25,Regular,0.022922,Baking Goods,240.7538,OUT013,1987,High,Tier 3,Supermarket Type1,3364.9532
5930,NCA18,10.10,Low Fat,0.056031,Household,115.1492,OUT013,1987,High,Tier 3,Supermarket Type1,1737.7380

In [14]:
print(data_BM.columns)

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [17]:
data_BM.columns = data_BM.columns.str.strip()

In [18]:
#sorting by descending order 

data_BM.sort_values(by='Outlet_Establishment_Year', ascending=False, inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
2825,FDL16,12.85,Low Fat,0.169139,Frozen Foods,46.4060,OUT018,2009,Medium,Tier 3,Supermarket Type2,186.4240
7389,NCD42,16.50,Low Fat,0.012689,Health and Hygiene,39.7506,OUT018,2009,Medium,Tier 3,Supermarket Type2,227.7036
2165,DRJ39,20.25,Low Fat,0.036474,Dairy,218.3482,OUT018,2009,Medium,Tier 3,Supermarket Type2,2409.5302
2162,FDR60,14.30,Low Fat,0.130946,Baking Goods,76.7328,OUT018,2009,Medium,Tier 3,Supermarket Type2,1312.9576
2158,FDM58,16.85,Regular,0.080015,Snack Foods,111.8544,OUT018,2009,Medium,Tier 3,Supermarket Type2,1677.8160

SORT OF MULTIPLE COLUMNS

In [23]:
#Read the dataset

data_BM=pd.read_csv (r'C:\Users\HomePC\IntroPython\Pandas_Part_1\Pandas Part 1\bigmart_data.csv')
#drop the null values
data_BM= data_BM.dropna(how='any')

#sorting of multiple columns
data_BM.sort_values(by=['Outlet_Establishment_Year', 'Item_Outlet_Sales'], ascending=False) [:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
43,FDC02,21.35,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
2803,FDU51,20.20,Regular,0.096907,Meat,175.5028,OUT018,2009,Medium,Tier 3,Supermarket Type2,6729.9064
641,FDY51,12.50,Low Fat,0.081465,Meat,220.7798,OUT018,2009,Medium,Tier 3,Supermarket Type2,6611.3940
2282,NCX30,16.70,Low Fat,0.026729,Household,248.4776,OUT018,2009,Medium,Tier 3,Supermarket Type2,6439.6176
2887,FDR25,17.00,Regular,0.140090,Canned,265.1884,OUT018,2009,Medium,Tier 3,Supermarket Type2,6359.7216

In [24]:
data_BM.sort_values(by=['Item_Outlet_Sales' ,'Outlet_Establishment_Year'], ascending=False, inplace=True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
4888,FDF39,14.850,Regular,0.019495,Dairy,261.2910,OUT013,1987,High,Tier 3,Supermarket Type1,10256.6490
4289,NCM05,6.825,Low Fat,0.059847,Health and Hygiene,262.5226,OUT046,1997,Small,Tier 1,Supermarket Type1,9779.9362
6409,FDA21,13.650,Low Fat,0.035931,Snack Foods,184.4924,OUT013,1987,High,Tier 3,Supermarket Type1,9069.5276
4991,NCQ53,17.600,Low Fat,0.018905,Health and Hygiene,234.6590,OUT046,1997,Small,Tier 1,Supermarket Type1,8508.9240
5752,FDI15,13.800,Low Fat,0.141326,Dairy,265.0884,OUT035,2004,Small,Tier 2,Supermarket Type1,8479.6288

SORTING USING sort_index()
When we sort by index with inplace = TRUE option and retrieve we retrieve the original dataframe

In [25]:
data_BM.sort_index(inplace= True)
data_BM[:5]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088